[package]
name = "neurons"
version = "0.0.1"
edition = "2021"
description = "A simple neural network implementation in Rust"
authors = ["Hallvard Høyland Lavik"]
homepage = "https://github.com/hallvardnmbu/neurons"
readme = "README.txt"
license = "Apache-2.0"
repository = "https://github.com/hallvardnmbu/neurons"
include = ["**/*.rs", "Carg.toml"]

[dependencies]

[[bin]]
name = "neurons"
path = "src/main.rs"
