[package]
name = "neurons"
version = "0.1.0"
edition = "2021"
description = "Modular neural network in Rust."
authors = ["Hallvard Høyland Lavik"]
homepage = "https://github.com/hallvardnmbu/neurons"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/hallvardnmbu/neurons"
include = ["**/*.rs", "Cargo.toml", "neurons.css"]

[package.metadata.docs.rs]
rustdoc-args = ["--theme", "neurons.css"]

[dependencies]
rand = "0.8.5"
csv = "1.3.0"

[[example]]
name = "example_network"
path = "examples/example_network.rs"

[[example]]
name = "example_xor"
path = "examples/example_xor.rs"

[[example]]
name = "example_iris"
path = "examples/example_iris.rs"

[[example]]
name = "testing"
path = "examples/testing.rs"
