[package]
name = "neurons"
version = "0.1.1"
edition = "2021"
description = "Modular neural network in Rust."
authors = ["Hallvard Høyland Lavik"]
homepage = "https://github.com/hallvardnmbu/neurons"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/hallvardnmbu/neurons"
include = ["**/*.rs", "Cargo.toml", "neurons.css"]

[package.metadata.docs.rs]
rustdoc-args = ["--theme", "neurons.css"]

[dependencies]
csv = "1.3.0"
plotters = "0.3.6"

[dev-dependencies]
approx = "0.5.1"

[[example]]
name = "example_network"
path = "examples/example_network.rs"

[[example]]
name = "example_xor"
path = "examples/example_xor.rs"

[[example]]
name = "example_iris"
path = "examples/example_iris.rs"

[[example]]
name = "example_convolution"
path = "examples/example_convolution.rs"
